
#line 3 "lex.jj.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define jjconst const
#else
#define jjconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (jj_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((jj_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE jjrestart(jjin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(jj_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct jj_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t jj_size_t;
#endif

extern jj_size_t jjleng;

extern FILE *jjin, *jjout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define jjless(n) \
	do \
		{ \
		/* Undo effects of setting up jjtext. */ \
        int jjless_macro_arg = (n); \
        YY_LESS_LINENO(jjless_macro_arg);\
		*jj_cp = (jj_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(jj_c_buf_p) = jj_cp = jj_bp + jjless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up jjtext again */ \
		} \
	while ( 0 )

#define unput(c) jjunput( c, (jjtext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct jj_buffer_state
	{
	FILE *jj_input_file;

	char *jj_ch_buf;		/* input buffer */
	char *jj_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	jj_size_t jj_buf_size;

	/* Number of characters read into jj_ch_buf, not including EOB
	 * characters.
	 */
	jj_size_t jj_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int jj_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int jj_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int jj_at_bol;

    int jj_bs_lineno; /**< The line count. */
    int jj_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int jj_fill_buffer;

	int jj_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via jjrestart()), so that the user can continue scanning by
	 * just pointing jjin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t jj_buffer_stack_top = 0; /**< index of top of stack. */
static size_t jj_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * jj_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (jj_buffer_stack) \
                          ? (jj_buffer_stack)[(jj_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (jj_buffer_stack)[(jj_buffer_stack_top)]

/* jj_hold_char holds the character lost when jjtext is formed. */
static char jj_hold_char;
static jj_size_t jj_n_chars;		/* number of characters read into jj_ch_buf */
jj_size_t jjleng;

/* Points to current character in buffer. */
static char *jj_c_buf_p = (char *) 0;
static int jj_init = 0;		/* whether we need to initialize */
static int jj_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh jjin.  A bit of a hack ...
 */
static int jj_did_buffer_switch_on_eof;

void jjrestart (FILE *input_file  );
void jj_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE jj_create_buffer (FILE *file,int size  );
void jj_delete_buffer (YY_BUFFER_STATE b  );
void jj_flush_buffer (YY_BUFFER_STATE b  );
void jjpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void jjpop_buffer_state (void );

static void jjensure_buffer_stack (void );
static void jj_load_buffer_state (void );
static void jj_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER jj_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE jj_scan_buffer (char *base,jj_size_t size  );
YY_BUFFER_STATE jj_scan_string (jjconst char *jj_str  );
YY_BUFFER_STATE jj_scan_bytes (jjconst char *bytes,jj_size_t len  );

void *jjalloc (jj_size_t  );
void *jjrealloc (void *,jj_size_t  );
void jjfree (void *  );

#define jj_new_buffer jj_create_buffer

#define jj_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        jjensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            jj_create_buffer(jjin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->jj_is_interactive = is_interactive; \
	}

#define jj_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        jjensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            jj_create_buffer(jjin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->jj_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->jj_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *jjin = (FILE *) 0, *jjout = (FILE *) 0;

typedef int jj_state_type;

extern int jjlineno;

int jjlineno = 1;

extern char *jjtext;
#define jjtext_ptr jjtext

static jj_state_type jj_get_previous_state (void );
static jj_state_type jj_try_NUL_trans (jj_state_type current_state  );
static int jj_get_next_buffer (void );
static void jj_fatal_error (jjconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up jjtext.
 */
#define YY_DO_BEFORE_ACTION \
	(jjtext_ptr) = jj_bp; \
	jjleng = (size_t) (jj_cp - jj_bp); \
	(jj_hold_char) = *jj_cp; \
	*jj_cp = '\0'; \
	(jj_c_buf_p) = jj_cp;

#define YY_NUM_RULES 57
#define YY_END_OF_BUFFER 58
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct jj_trans_info
	{
	flex_int32_t jj_verify;
	flex_int32_t jj_nxt;
	};
static jjconst flex_int16_t jj_accept[107] =
    {   0,
        0,    0,   58,   57,    1,   56,   14,    3,   10,   22,
       23,    8,    6,   16,    7,   15,    9,   53,    4,    5,
       19,   26,   21,   55,   55,   55,   34,   24,   25,   11,
        2,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   12,   35,   13,   57,    0,   53,   18,
       17,   20,   55,   55,   55,   55,   55,   38,   55,   55,
       55,   55,   55,   55,   36,   50,   55,   55,   37,   55,
        0,    0,    0,    0,    0,    0,    0,   54,   55,   39,
       51,   55,   55,   55,   40,   45,   46,   47,   44,   55,
       55,   33,   30,   31,   29,   32,   28,   27,   55,   42,

       49,   41,   43,   48,   52,    0
    } ;

static jjconst flex_int32_t jj_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    1,    5,    1,    6,    1,    3,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   16,   17,   18,
       19,   20,    1,    1,   21,   21,   21,   22,   21,   23,
       21,   24,   25,   21,   21,   26,   21,   21,   21,   21,
       21,   21,   27,   21,   28,   21,   21,   21,   21,   21,
       29,    1,   30,   31,   32,    1,   33,   34,   35,   36,

       37,   38,   21,   39,   40,   41,   42,   21,   43,   44,
       45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
       21,   55,   56,   57,   58,   59,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static jjconst flex_int32_t jj_meta[61] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    2,    1,    1,    1,    1,    1,
        2,    2,    2,    2,    2,    2,    2,    2,    1,    1,
        1,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    1,    1,    1,    1,    1
    } ;

static jjconst flex_int16_t jj_base[108] =
    {   0,
        0,    0,  122,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,   48,  123,  123,
       45,  123,  102,    0,   94,   97,    0,  123,  123,  123,
      123,   74,   72,  109,   63,   81,   26,   33,   64,   68,
       64,  107,   70,  123,  123,  123,   33,   93,   64,  123,
      123,  123,    0,   79,  104,   69,   61,  123,   66,   67,
       99,   48,   45,   54,  123,    0,   44,   48,  123,   58,
       91,   90,   89,   88,   87,   86,   84,   70,   57,  123,
        0,   49,   34,   31,  123,    0,    0,    0,    0,   30,
       34,  123,  123,  123,  123,  123,  123,  123,   48,    0,

        0,    0,    0,    0,    0,  123,   67
    } ;

static jjconst flex_int16_t jj_def[108] =
    {   0,
      106,    1,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  107,  107,  107,  107,  106,  106,  106,
      106,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  107,  107,  107,  107,  107,  106,  107,  107,
      107,  107,  107,  107,  106,  107,  107,  107,  106,  107,
      106,  106,  106,  106,  106,  106,  106,  106,  107,  106,
      107,  107,  107,  107,  106,  107,  107,  107,  107,  107,
      107,  106,  106,  106,  106,  106,  106,  106,  107,  107,

      107,  107,  107,  107,  107,    0,  106
    } ;

static jjconst flex_int16_t jj_nxt[184] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   24,   25,   24,   26,   24,   27,   24,   28,   29,
       30,   31,   32,   24,   33,   34,   35,   36,   24,   37,
       24,   24,   38,   24,   39,   40,   24,   24,   41,   24,
       42,   24,   43,   24,   24,   44,   45,   46,   47,    6,
       48,   61,   49,   50,   51,   63,   65,   71,   53,   62,
       72,  105,   64,   73,   74,   75,   48,  104,   49,  103,
      102,  101,  100,   99,   78,   76,   98,   77,   97,   96,
       95,   94,   93,   92,   91,   90,   89,   88,   87,   86,

       85,   84,   83,   82,   81,   80,   79,   78,   70,   69,
       68,   66,   67,   60,   59,   58,   57,   56,   55,   54,
       52,  106,    3,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106
    } ;

static jjconst flex_int16_t jj_chk[184] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       18,   37,   18,   21,   21,   38,   39,   47,  107,   37,
       47,   99,   38,   47,   47,   47,   49,   91,   49,   90,
       84,   83,   82,   79,   78,   47,   77,   47,   76,   75,
       74,   73,   72,   71,   70,   68,   67,   64,   63,   62,

       61,   60,   59,   57,   56,   55,   54,   48,   43,   42,
       41,   39,   40,   36,   35,   34,   33,   32,   26,   25,
       23,    3,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106
    } ;

static jj_state_type jj_last_accepting_state;
static char *jj_last_accepting_cpos;

extern int jj_flex_debug;
int jj_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define jjmore() jjmore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *jjtext;
#line 1 "TRANSL/wn.lex"
#line 535 "lex.jj.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int jj_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int jjlex_destroy (void );

int jjget_debug (void );

void jjset_debug (int debug_flag  );

YY_EXTRA_TYPE jjget_extra (void );

void jjset_extra (YY_EXTRA_TYPE user_defined  );

FILE *jjget_in (void );

void jjset_in  (FILE * in_str  );

FILE *jjget_out (void );

void jjset_out  (FILE * out_str  );

jj_size_t jjget_leng (void );

char *jjget_text (void );

int jjget_lineno (void );

void jjset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void jjunput (int c,char *buf_ptr  );
    
#ifndef jjtext_ptr
static void jj_flex_strncpy (char *,jjconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int jj_flex_strlen (jjconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int jjinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( jjtext, jjleng, 1, jjout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->jj_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( jjin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( jjin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, jjin))==0 && ferror(jjin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(jjin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "jjterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef jjterminate
#define jjterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) jj_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int jjlex (void);

#define YY_DECL int jjlex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after jjtext and jjleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register jj_state_type jj_current_state;
	register char *jj_cp, *jj_bp;
	register int jj_act;
    
	if ( !(jj_init) )
		{
		(jj_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (jj_start) )
			(jj_start) = 1;	/* first start state */

		if ( ! jjin )
			jjin = stdin;

		if ( ! jjout )
			jjout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			jjensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				jj_create_buffer(jjin,YY_BUF_SIZE );
		}

		jj_load_buffer_state( );
		}

	{
#line 4 "TRANSL/wn.lex"

#line 751 "lex.jj.c"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		jj_cp = (jj_c_buf_p);

		/* Support of jjtext. */
		*jj_cp = (jj_hold_char);

		/* jj_bp points to the position in jj_ch_buf of the start of
		 * the current run.
		 */
		jj_bp = jj_cp;

		jj_current_state = (jj_start);
jj_match:
		do
			{
			register YY_CHAR jj_c = jj_ec[YY_SC_TO_UI(*jj_cp)] ;
			if ( jj_accept[jj_current_state] )
				{
				(jj_last_accepting_state) = jj_current_state;
				(jj_last_accepting_cpos) = jj_cp;
				}
			while ( jj_chk[jj_base[jj_current_state] + jj_c] != jj_current_state )
				{
				jj_current_state = (int) jj_def[jj_current_state];
				if ( jj_current_state >= 107 )
					jj_c = jj_meta[(unsigned int) jj_c];
				}
			jj_current_state = jj_nxt[jj_base[jj_current_state] + (unsigned int) jj_c];
			++jj_cp;
			}
		while ( jj_base[jj_current_state] != 123 );

jj_find_action:
		jj_act = jj_accept[jj_current_state];
		if ( jj_act == 0 )
			{ /* have to back up */
			jj_cp = (jj_last_accepting_cpos);
			jj_current_state = (jj_last_accepting_state);
			jj_act = jj_accept[jj_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( jj_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*jj_cp = (jj_hold_char);
			jj_cp = (jj_last_accepting_cpos);
			jj_current_state = (jj_last_accepting_state);
			goto jj_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 5 "TRANSL/wn.lex"
{ ungetc((char)0,jjin);
                        /*return(NEWLINE);*/ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 7 "TRANSL/wn.lex"
{ return(UNDERSCORE);  }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 8 "TRANSL/wn.lex"
{ return(DIESIS);      }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 9 "TRANSL/wn.lex"
{ return(COLON);       }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 10 "TRANSL/wn.lex"
{ return(SEMICOLON);   }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 11 "TRANSL/wn.lex"
{ return(PLUS);        }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 12 "TRANSL/wn.lex"
{ return(MINUS);       }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 13 "TRANSL/wn.lex"
{ return(MOLT);        }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 14 "TRANSL/wn.lex"
{ return(DIV);         }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 15 "TRANSL/wn.lex"
{ return(DISTANCE);    }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 16 "TRANSL/wn.lex"
{ return(CARET);       }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 17 "TRANSL/wn.lex"
{ return(OBRCS);       }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 18 "TRANSL/wn.lex"
{ return(CBRCS);       }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 19 "TRANSL/wn.lex"
{ return(ESCL);        }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 20 "TRANSL/wn.lex"
{ return(POINT);       }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 21 "TRANSL/wn.lex"
{ return(COMMA);       }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 22 "TRANSL/wn.lex"
{ return(NE);          }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 23 "TRANSL/wn.lex"
{ return(LE);          }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 24 "TRANSL/wn.lex"
{ return(LT);      }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 25 "TRANSL/wn.lex"
{ return(GE);          }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 26 "TRANSL/wn.lex"
{ return(GT);     }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 27 "TRANSL/wn.lex"
{ /*fprintf(stdout,"(\n");*/return(OPAR);        }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 28 "TRANSL/wn.lex"
{ /*fprintf(stdout,")\n");*/return(CPAR);        }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 29 "TRANSL/wn.lex"
{ /*fprintf(stdout,"[\n");*/return(OBRCK);       }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 30 "TRANSL/wn.lex"
{ /*fprintf(stdout,"]\n");*/return(CBRCK);       }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 31 "TRANSL/wn.lex"
{ /*fprintf(stdout,"=\n");*/return(EQ);       }
	YY_BREAK
case 27:
*jj_cp = (jj_hold_char); /* undo effects of setting up jjtext */
(jj_c_buf_p) = jj_cp = jj_bp + 2;
YY_DO_BEFORE_ACTION; /* set up jjtext again */
YY_RULE_SETUP
#line 32 "TRANSL/wn.lex"
{ 
			parsing_flag = MDRATE;
			return(MD);	     
		      }
	YY_BREAK
case 28:
*jj_cp = (jj_hold_char); /* undo effects of setting up jjtext */
(jj_c_buf_p) = jj_cp = jj_bp + 2;
YY_DO_BEFORE_ACTION; /* set up jjtext again */
YY_RULE_SETUP
#line 36 "TRANSL/wn.lex"
{ 
			parsing_flag = PLACE;
			return(PD);	     
		      }
	YY_BREAK
case 29:
*jj_cp = (jj_hold_char); /* undo effects of setting up jjtext */
(jj_c_buf_p) = jj_cp = jj_bp + 2;
YY_DO_BEFORE_ACTION; /* set up jjtext again */
YY_RULE_SETUP
#line 40 "TRANSL/wn.lex"
{
			/*fprintf(stdout,"~k\n");*/parsing_flag = TRANSITION;
			return(TD);	     
		      }
	YY_BREAK
case 30:
*jj_cp = (jj_hold_char); /* undo effects of setting up jjtext */
(jj_c_buf_p) = jj_cp = jj_bp + 2;
YY_DO_BEFORE_ACTION; /* set up jjtext again */
YY_RULE_SETUP
#line 44 "TRANSL/wn.lex"
{
			parsing_flag = FUNCTION;
			return(FU);	     
		      }
	YY_BREAK
case 31:
*jj_cp = (jj_hold_char); /* undo effects of setting up jjtext */
(jj_c_buf_p) = jj_cp = jj_bp + 2;
YY_DO_BEFORE_ACTION; /* set up jjtext again */
YY_RULE_SETUP
#line 48 "TRANSL/wn.lex"
{ 
			parsing_flag = DYNAMIC_SUBCLASS;
			return(DSC);	     
	              }
	YY_BREAK
case 32:
*jj_cp = (jj_hold_char); /* undo effects of setting up jjtext */
(jj_c_buf_p) = jj_cp = jj_bp + 2;
YY_DO_BEFORE_ACTION; /* set up jjtext again */
YY_RULE_SETUP
#line 52 "TRANSL/wn.lex"
{ 
			parsing_flag = INITIAL_MARKING;
			return(MA);	     
	              }
	YY_BREAK
case 33:
*jj_cp = (jj_hold_char); /* undo effects of setting up jjtext */
(jj_c_buf_p) = jj_cp = jj_bp + 2;
YY_DO_BEFORE_ACTION; /* set up jjtext again */
YY_RULE_SETUP
#line 56 "TRANSL/wn.lex"
{ 
			parsing_flag = COLOR_CLASS;
			return(CO);	     
		      }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 60 "TRANSL/wn.lex"
{ return(S);           }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 61 "TRANSL/wn.lex"
{ return(VBAR);        }
	YY_BREAK
case 36:
*jj_cp = (jj_hold_char); /* undo effects of setting up jjtext */
(jj_c_buf_p) = jj_cp = jj_bp + 1;
YY_DO_BEFORE_ACTION; /* set up jjtext again */
YY_RULE_SETUP
#line 62 "TRANSL/wn.lex"
{ 
			str_val = ORDERED ;
			return(O) ;
		      }
	YY_BREAK
case 37:
*jj_cp = (jj_hold_char); /* undo effects of setting up jjtext */
(jj_c_buf_p) = jj_cp = jj_bp + 1;
YY_DO_BEFORE_ACTION; /* set up jjtext again */
YY_RULE_SETUP
#line 66 "TRANSL/wn.lex"
{ 
			str_val = UNORDERED;
			return(US);
		      }
	YY_BREAK
case 38:
*jj_cp = (jj_hold_char); /* undo effects of setting up jjtext */
(jj_c_buf_p) = jj_cp = jj_bp + 1;
YY_DO_BEFORE_ACTION; /* set up jjtext again */
YY_RULE_SETUP
#line 70 "TRANSL/wn.lex"
{ /*fprintf(stdout,"d\n");*/return(D);           }
	YY_BREAK
case 39:
/* rule 39 can match eol */
*jj_cp = (jj_hold_char); /* undo effects of setting up jjtext */
YY_LINENO_REWIND_TO(jj_bp + 2);
(jj_c_buf_p) = jj_cp = jj_bp + 2;
YY_DO_BEFORE_ACTION; /* set up jjtext again */
YY_RULE_SETUP
#line 71 "TRANSL/wn.lex"
{ return(ID);          }
	YY_BREAK
case 40:
/* rule 40 can match eol */
*jj_cp = (jj_hold_char); /* undo effects of setting up jjtext */
YY_LINENO_REWIND_TO(jj_bp + 2);
(jj_c_buf_p) = jj_cp = jj_bp + 2;
YY_DO_BEFORE_ACTION; /* set up jjtext again */
YY_RULE_SETUP
#line 72 "TRANSL/wn.lex"
{ return(ID);          }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 73 "TRANSL/wn.lex"
{ return(FACT);        }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 74 "TRANSL/wn.lex"
{ return(COMB);        }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 75 "TRANSL/wn.lex"
{ return(SQRT);        }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 76 "TRANSL/wn.lex"
{ return(POW);         }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 77 "TRANSL/wn.lex"
{ return(INV);         }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 78 "TRANSL/wn.lex"
{ return(MAXT);         }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 79 "TRANSL/wn.lex"
{ return(MINT);         }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 80 "TRANSL/wn.lex"
{ return(WHEN);        }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 81 "TRANSL/wn.lex"
{ return(EVER);        }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 82 "TRANSL/wn.lex"
{ return(OR);          }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 83 "TRANSL/wn.lex"
{ /*fprintf(stdout,"and\n");*/return(AND);	     }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 84 "TRANSL/wn.lex"
{ return(FLUSH);	     }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 85 "TRANSL/wn.lex"
{ 
			str_val = atoi(jjtext) ;
			return(NUM);
		      }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 89 "TRANSL/wn.lex"
{ 
			real_val = strtod(jjtext,(char **)NULL) ;
			return(REALNUM);
		      }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 93 "TRANSL/wn.lex"
{ 
			strcpy(str_in,jjtext) ;
			 /*fprintf(stdout,"STRING\n");*/return(STRING);
		      }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 97 "TRANSL/wn.lex"
{
                        /* Do NOTHING !! DO NOT ECHO ON STDOUT !!! */
                      }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 100 "TRANSL/wn.lex"
ECHO;
	YY_BREAK
#line 1173 "lex.jj.c"
case YY_STATE_EOF(INITIAL):
	jjterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int jj_amount_of_matched_text = (int) (jj_cp - (jjtext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*jj_cp = (jj_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->jj_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed jjin at a new source and called
			 * jjlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(jj_n_chars) = YY_CURRENT_BUFFER_LVALUE->jj_n_chars;
			YY_CURRENT_BUFFER_LVALUE->jj_input_file = jjin;
			YY_CURRENT_BUFFER_LVALUE->jj_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for jj_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since jj_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (jj_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->jj_ch_buf[(jj_n_chars)] )
			{ /* This was really a NUL. */
			jj_state_type jj_next_state;

			(jj_c_buf_p) = (jjtext_ptr) + jj_amount_of_matched_text;

			jj_current_state = jj_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * jj_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			jj_next_state = jj_try_NUL_trans( jj_current_state );

			jj_bp = (jjtext_ptr) + YY_MORE_ADJ;

			if ( jj_next_state )
				{
				/* Consume the NUL. */
				jj_cp = ++(jj_c_buf_p);
				jj_current_state = jj_next_state;
				goto jj_match;
				}

			else
				{
				jj_cp = (jj_c_buf_p);
				goto jj_find_action;
				}
			}

		else switch ( jj_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(jj_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * jj_get_next_buffer() to have set up
					 * jjtext, we can now set up
					 * jj_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(jj_c_buf_p) = (jjtext_ptr) + YY_MORE_ADJ;

					jj_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (jj_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(jj_c_buf_p) =
					(jjtext_ptr) + jj_amount_of_matched_text;

				jj_current_state = jj_get_previous_state(  );

				jj_cp = (jj_c_buf_p);
				jj_bp = (jjtext_ptr) + YY_MORE_ADJ;
				goto jj_match;

			case EOB_ACT_LAST_MATCH:
				(jj_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->jj_ch_buf[(jj_n_chars)];

				jj_current_state = jj_get_previous_state(  );

				jj_cp = (jj_c_buf_p);
				jj_bp = (jjtext_ptr) + YY_MORE_ADJ;
				goto jj_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of jjlex */

/* jj_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int jj_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->jj_ch_buf;
	register char *source = (jjtext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (jj_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->jj_ch_buf[(jj_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->jj_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (jj_c_buf_p) - (jjtext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((jj_c_buf_p) - (jjtext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->jj_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->jj_n_chars = (jj_n_chars) = 0;

	else
		{
			jj_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->jj_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int jj_c_buf_p_offset =
				(int) ((jj_c_buf_p) - b->jj_ch_buf);

			if ( b->jj_is_our_buffer )
				{
				jj_size_t new_size = b->jj_buf_size * 2;

				if ( new_size <= 0 )
					b->jj_buf_size += b->jj_buf_size / 8;
				else
					b->jj_buf_size *= 2;

				b->jj_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					jjrealloc((void *) b->jj_ch_buf,b->jj_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->jj_ch_buf = 0;

			if ( ! b->jj_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(jj_c_buf_p) = &b->jj_ch_buf[jj_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->jj_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->jj_ch_buf[number_to_move]),
			(jj_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->jj_n_chars = (jj_n_chars);
		}

	if ( (jj_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			jjrestart(jjin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->jj_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((jj_size_t) ((jj_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->jj_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		jj_size_t new_size = (jj_n_chars) + number_to_move + ((jj_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->jj_ch_buf = (char *) jjrealloc((void *) YY_CURRENT_BUFFER_LVALUE->jj_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->jj_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in jj_get_next_buffer()" );
	}

	(jj_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->jj_ch_buf[(jj_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->jj_ch_buf[(jj_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(jjtext_ptr) = &YY_CURRENT_BUFFER_LVALUE->jj_ch_buf[0];

	return ret_val;
}

/* jj_get_previous_state - get the state just before the EOB char was reached */

    static jj_state_type jj_get_previous_state (void)
{
	register jj_state_type jj_current_state;
	register char *jj_cp;
    
	jj_current_state = (jj_start);

	for ( jj_cp = (jjtext_ptr) + YY_MORE_ADJ; jj_cp < (jj_c_buf_p); ++jj_cp )
		{
		register YY_CHAR jj_c = (*jj_cp ? jj_ec[YY_SC_TO_UI(*jj_cp)] : 60);
		if ( jj_accept[jj_current_state] )
			{
			(jj_last_accepting_state) = jj_current_state;
			(jj_last_accepting_cpos) = jj_cp;
			}
		while ( jj_chk[jj_base[jj_current_state] + jj_c] != jj_current_state )
			{
			jj_current_state = (int) jj_def[jj_current_state];
			if ( jj_current_state >= 107 )
				jj_c = jj_meta[(unsigned int) jj_c];
			}
		jj_current_state = jj_nxt[jj_base[jj_current_state] + (unsigned int) jj_c];
		}

	return jj_current_state;
}

/* jj_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = jj_try_NUL_trans( current_state );
 */
    static jj_state_type jj_try_NUL_trans  (jj_state_type jj_current_state )
{
	register int jj_is_jam;
    	register char *jj_cp = (jj_c_buf_p);

	register YY_CHAR jj_c = 60;
	if ( jj_accept[jj_current_state] )
		{
		(jj_last_accepting_state) = jj_current_state;
		(jj_last_accepting_cpos) = jj_cp;
		}
	while ( jj_chk[jj_base[jj_current_state] + jj_c] != jj_current_state )
		{
		jj_current_state = (int) jj_def[jj_current_state];
		if ( jj_current_state >= 107 )
			jj_c = jj_meta[(unsigned int) jj_c];
		}
	jj_current_state = jj_nxt[jj_base[jj_current_state] + (unsigned int) jj_c];
	jj_is_jam = (jj_current_state == 106);

		return jj_is_jam ? 0 : jj_current_state;
}

    static void jjunput (int c, register char * jj_bp )
{
	register char *jj_cp;
    
    jj_cp = (jj_c_buf_p);

	/* undo effects of setting up jjtext */
	*jj_cp = (jj_hold_char);

	if ( jj_cp < YY_CURRENT_BUFFER_LVALUE->jj_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register jj_size_t number_to_move = (jj_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->jj_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->jj_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->jj_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->jj_ch_buf )
			*--dest = *--source;

		jj_cp += (int) (dest - source);
		jj_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->jj_n_chars =
			(jj_n_chars) = YY_CURRENT_BUFFER_LVALUE->jj_buf_size;

		if ( jj_cp < YY_CURRENT_BUFFER_LVALUE->jj_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--jj_cp = (char) c;

	(jjtext_ptr) = jj_bp;
	(jj_hold_char) = *jj_cp;
	(jj_c_buf_p) = jj_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int jjinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(jj_c_buf_p) = (jj_hold_char);

	if ( *(jj_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* jj_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (jj_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->jj_ch_buf[(jj_n_chars)] )
			/* This was really a NUL. */
			*(jj_c_buf_p) = '\0';

		else
			{ /* need more input */
			jj_size_t offset = (jj_c_buf_p) - (jjtext_ptr);
			++(jj_c_buf_p);

			switch ( jj_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because jj_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					jjrestart(jjin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (jj_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return jjinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(jj_c_buf_p) = (jjtext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (jj_c_buf_p);	/* cast for 8-bit char's */
	*(jj_c_buf_p) = '\0';	/* preserve jjtext */
	(jj_hold_char) = *++(jj_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void jjrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        jjensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            jj_create_buffer(jjin,YY_BUF_SIZE );
	}

	jj_init_buffer(YY_CURRENT_BUFFER,input_file );
	jj_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void jj_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		jjpop_buffer_state();
	 *		jjpush_buffer_state(new_buffer);
     */
	jjensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(jj_c_buf_p) = (jj_hold_char);
		YY_CURRENT_BUFFER_LVALUE->jj_buf_pos = (jj_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->jj_n_chars = (jj_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	jj_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(jj_did_buffer_switch_on_eof) = 1;
}

static void jj_load_buffer_state  (void)
{
    	(jj_n_chars) = YY_CURRENT_BUFFER_LVALUE->jj_n_chars;
	(jjtext_ptr) = (jj_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->jj_buf_pos;
	jjin = YY_CURRENT_BUFFER_LVALUE->jj_input_file;
	(jj_hold_char) = *(jj_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE jj_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) jjalloc(sizeof( struct jj_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in jj_create_buffer()" );

	b->jj_buf_size = size;

	/* jj_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->jj_ch_buf = (char *) jjalloc(b->jj_buf_size + 2  );
	if ( ! b->jj_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in jj_create_buffer()" );

	b->jj_is_our_buffer = 1;

	jj_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with jj_create_buffer()
 * 
 */
    void jj_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->jj_is_our_buffer )
		jjfree((void *) b->jj_ch_buf  );

	jjfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a jjrestart() or at EOF.
 */
    static void jj_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	jj_flush_buffer(b );

	b->jj_input_file = file;
	b->jj_fill_buffer = 1;

    /* If b is the current buffer, then jj_init_buffer was _probably_
     * called from jjrestart() or through jj_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->jj_bs_lineno = 1;
        b->jj_bs_column = 0;
    }

        b->jj_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void jj_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->jj_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->jj_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->jj_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->jj_buf_pos = &b->jj_ch_buf[0];

	b->jj_at_bol = 1;
	b->jj_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		jj_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void jjpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	jjensure_buffer_stack();

	/* This block is copied from jj_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(jj_c_buf_p) = (jj_hold_char);
		YY_CURRENT_BUFFER_LVALUE->jj_buf_pos = (jj_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->jj_n_chars = (jj_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(jj_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from jj_switch_to_buffer. */
	jj_load_buffer_state( );
	(jj_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void jjpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	jj_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((jj_buffer_stack_top) > 0)
		--(jj_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		jj_load_buffer_state( );
		(jj_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void jjensure_buffer_stack (void)
{
	jj_size_t num_to_alloc;
    
	if (!(jj_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(jj_buffer_stack) = (struct jj_buffer_state**)jjalloc
								(num_to_alloc * sizeof(struct jj_buffer_state*)
								);
		if ( ! (jj_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in jjensure_buffer_stack()" );
								  
		memset((jj_buffer_stack), 0, num_to_alloc * sizeof(struct jj_buffer_state*));
				
		(jj_buffer_stack_max) = num_to_alloc;
		(jj_buffer_stack_top) = 0;
		return;
	}

	if ((jj_buffer_stack_top) >= ((jj_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (jj_buffer_stack_max) + grow_size;
		(jj_buffer_stack) = (struct jj_buffer_state**)jjrealloc
								((jj_buffer_stack),
								num_to_alloc * sizeof(struct jj_buffer_state*)
								);
		if ( ! (jj_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in jjensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((jj_buffer_stack) + (jj_buffer_stack_max), 0, grow_size * sizeof(struct jj_buffer_state*));
		(jj_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE jj_scan_buffer  (char * base, jj_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) jjalloc(sizeof( struct jj_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in jj_scan_buffer()" );

	b->jj_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->jj_buf_pos = b->jj_ch_buf = base;
	b->jj_is_our_buffer = 0;
	b->jj_input_file = 0;
	b->jj_n_chars = b->jj_buf_size;
	b->jj_is_interactive = 0;
	b->jj_at_bol = 1;
	b->jj_fill_buffer = 0;
	b->jj_buffer_status = YY_BUFFER_NEW;

	jj_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to jjlex() will
 * scan from a @e copy of @a str.
 * @param jjstr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       jj_scan_bytes() instead.
 */
YY_BUFFER_STATE jj_scan_string (jjconst char * jjstr )
{
    
	return jj_scan_bytes(jjstr,strlen(jjstr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to jjlex() will
 * scan from a @e copy of @a bytes.
 * @param jjbytes the byte buffer to scan
 * @param _jjbytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE jj_scan_bytes  (jjconst char * jjbytes, jj_size_t  _jjbytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	jj_size_t n;
	jj_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _jjbytes_len + 2;
	buf = (char *) jjalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in jj_scan_bytes()" );

	for ( i = 0; i < _jjbytes_len; ++i )
		buf[i] = jjbytes[i];

	buf[_jjbytes_len] = buf[_jjbytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = jj_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in jj_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->jj_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void jj_fatal_error (jjconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine jjless() so it works in section 3 code. */

#undef jjless
#define jjless(n) \
	do \
		{ \
		/* Undo effects of setting up jjtext. */ \
        int jjless_macro_arg = (n); \
        YY_LESS_LINENO(jjless_macro_arg);\
		jjtext[jjleng] = (jj_hold_char); \
		(jj_c_buf_p) = jjtext + jjless_macro_arg; \
		(jj_hold_char) = *(jj_c_buf_p); \
		*(jj_c_buf_p) = '\0'; \
		jjleng = jjless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int jjget_lineno  (void)
{
        
    return jjlineno;
}

/** Get the input stream.
 * 
 */
FILE *jjget_in  (void)
{
        return jjin;
}

/** Get the output stream.
 * 
 */
FILE *jjget_out  (void)
{
        return jjout;
}

/** Get the length of the current token.
 * 
 */
jj_size_t jjget_leng  (void)
{
        return jjleng;
}

/** Get the current token.
 * 
 */

char *jjget_text  (void)
{
        return jjtext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void jjset_lineno (int  line_number )
{
    
    jjlineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see jj_switch_to_buffer
 */
void jjset_in (FILE *  in_str )
{
        jjin = in_str ;
}

void jjset_out (FILE *  out_str )
{
        jjout = out_str ;
}

int jjget_debug  (void)
{
        return jj_flex_debug;
}

void jjset_debug (int  bdebug )
{
        jj_flex_debug = bdebug ;
}

static int jj_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from jjlex_destroy(), so don't allocate here.
     */

    (jj_buffer_stack) = 0;
    (jj_buffer_stack_top) = 0;
    (jj_buffer_stack_max) = 0;
    (jj_c_buf_p) = (char *) 0;
    (jj_init) = 0;
    (jj_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    jjin = stdin;
    jjout = stdout;
#else
    jjin = (FILE *) 0;
    jjout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * jjlex_init()
     */
    return 0;
}

/* jjlex_destroy is for both reentrant and non-reentrant scanners. */
int jjlex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		jj_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		jjpop_buffer_state();
	}

	/* Destroy the stack itself. */
	jjfree((jj_buffer_stack) );
	(jj_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * jjlex() is called, initialization will occur. */
    jj_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef jjtext_ptr
static void jj_flex_strncpy (char* s1, jjconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int jj_flex_strlen (jjconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *jjalloc (jj_size_t  size )
{
	return (void *) malloc( size );
}

void *jjrealloc  (void * ptr, jj_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void jjfree (void * ptr )
{
	free( (char *) ptr );	/* see jjrealloc() for (char *) cast */
}

#define YYTABLES_NAME "jjtables"

#line 100 "TRANSL/wn.lex"



